vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - copy:
          src: /ansible/ec2_deploy.yaml
          dest: /home/circleci/
          owner: foo
          group: foo
          mode: '0644'    
      - copy:
          src: /ansible/ansible.pem
          dest: /home/circleci/
          owner: foo
          group: foo
          mode: '0644'
      - run: pip3 install ansible boto boto3
      - run: chmod 400 ./ansible.pem
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ./ansible/ec2_deploy.yaml --user ubuntu --key-file ../ansible.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
           branches:
              only: master