vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
         fingerprints:
           - "88:1a:20:8c:04:7f:36:ac:f7:71:55:a3:c9:49:b8:68"
      - run: pip3 install ansible boto boto3
      - run: ansible-playbook ./ansible/ec2_deploy.yaml --ssh-common-args='-o StrictHostKeyChecking=no' --user ubuntu

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
           branches:
              only: master