vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run: chmod 400 ./ansible/ansible.pem
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ./ansible/ec2_deploy.yaml --user ubuntu --private-key MIIEowIBAAKCAQEAkY9qkUACv9qZ07qxw+2fDQSKyumC8fgF7cetjkFtQu996UpPui7+7+RgmlXVQY29ZOd6xcSttozK6wCTjYbpWBkRGLpF/8mWcue1dfe9oJYj8uzIqGH0oVs9sAH+o/fMy9EHiT0EcO3FQfRPN95YkRPhVbccK9wH4rFfKdR4x5wsp6aXR+c4ThVh8+BBoa14e9zbAHbfJulP0gobKRK8VSDymITqG4FquwWxvzyOFWSaf3n373rlui4OSJ/4JbdCM/A2J95zamWE0JOsj74yd57uzyfQLz/suIxGmxyWubq7r95PnxK8KTLktOhkvCs9xVdXwQbrUkxwxJ6xLPaGdwIDAQABAoIBAFLh69dbMHWX/sFN7AzZUBh0fqc9wZ8QECgt68g1vwY/Il3lP3KPcgCc9NjMiQqzr6U2HXVhIVzx3FVl1Z7ftBzC4TZIUrVsTuuMvom2kFZRR5T6eONQK6B5OK3w5NLutcFUe8sMYGwBJ7H/b+ArDhlFzagmBLeAqUjOoJZL8p4NlZ0MFiUpL1FqGCDx+WL11gUzPMBYIWUFTnlUS9RXdTcevFpmLwndHf2/hH+LI9si8+jv9fudw2rJ2SSN3dzhwFGHBu4JCJX7Q4tcUk0Cm5dQUJBAtdQVxkxAlLLf/s9oXl5dzwRAFqbGiN1Kz97pj3ntGDa52i5fx4A70JWMcDECgYEA1A+TctaIPD+Y+RHlQYr4eFoGO5DZb/0CckBY2iKJTkMT+90F6xERT4Y48g+2++EddYmIHz4oV6uaYwU1aWFK/iqG15UXbPxCgBRJd3Vxy++CZrgbgEIm4XuH43JcUyFmTIQRkohx0zpgNjBgxlYCtW516wOu3i4kKKP9snRXDD8CgYEAr7hsIz9busc4T+sUVq7DuNauprju186TxRdskS3GBhgQ2aECtVBy2AsSc6u2kuqWv+zYqjw7Y9hjl2bs237GzeM8WhOeXKB+tiDb+RSzcOAF/3LRUfW9R79ufpg6QLMS9YYQmMv4gFNjKL6MFt845w50RdOs5uiRsvnaKVr18kCgYBzj7FoiWRggL/aK1hlqVfSLizrVPpJPvWQUWSaKuvsTD2dqUrKWNi4H4r0zn+HL5wgKzyU2gieDhPqFjKPJMf7Ti2BWewUJjwPE/8dLFFBM1oXItUP+6JSa6/1ICBF5bRcuZVCyLUO1BBQYwVJkkLeNxMoMpdRqmUNtdlzhfQKBgCXZL1GYQAXHC1YLahoL1OasCcrPueWN6V1HIbdYHafO+E0MM7yxmm5X1LJBFmBmk9bt5JGHmf1ROM4VU4geVEvUd0M4GE8IXv7My+K55yvyxBBm1fWiN6asejIov97wf1iGUMtb2eBwL2fvYrwvuIK+D6X9wzHkf9uH59weZVAhAoGBAJcE+jLuc3REGVrTWw4Xaer667lywGwiheg5gQM0pCvd3JQDbgfWAp0M59R6WIAhe22Y3nfIlw93Xl22eIDKYEpivAWq3Rt73MkUvTmMUMyNkyGqlOixbCEDQqB75ffZTm0K1N7gOi6osKCRH2H+e6xygPZBE0QlKGkwIiwzl69p

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
           branches:
              only: master